title: Simongs NOTE
description: Personal NOTE
author: simongs
github: https://github.com/simongs
about: I'm WEB Programmer
disqus_shortname: simongs
google_analytics: UA-85442637-1

future: true
enableTags: true
tagarray: []

collections:
  project:
    output: false
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/simhongsup"
    - icon: fa-twitter
      link: "https://twitter.com/chopokmado"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/홍섭-심-aa315331"
    - icon: fa-stack-exchange
      link: "https://stackexchange.com/users/9363458/hongsup-sim"

share:
  twitter_username: chopokmado
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Github
      url: https://github.com/simongs
    - text: XML Feed
      url: /feed.xml

url: "https://simongs.github.io"
baseurl: ""
paginate: 5
per_page: 15
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist