title: Simongs NOTE
description: Personal NOTE
author: simongs
github: https://github.com/simongs
about: I'm WEB Programmer
disqus_shortname: simongs
google_analytics: UA-85442637-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-skype
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/chopokmado"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"

share:
  twitter_username: agusmakmun6
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Github
      url: https://github.com/simongs
    - text: XML Feed
      url: /feed.xml

url: "https://simongs.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist